install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.deb
  - sudo dpkg -i hugo_0.55.6_Linux-64bit.deb

script:
  - make build

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  skip_cleanup: true
  local_dir: public
  repo: airlab-unsri/airlab-unsri.github.io
  on:
    branch: master
